
export const products = [
  {
    _id: "1",
    name: 'PlayStation 5',
    price: 50000,
    discountPercent: 10,
    discountPrice: 45000,
    image: 'https://cdn.mos.cms.futurecdn.net/He8XmmZPXivi9EYTCpGLMW-768-80.jpg.webp',
    category: 'console',
    rating: 4.6,
    description: 'Experience the next generation of gaming with the PlayStation 5',
    trending: true
  },
  {
    _id: "2",
    name: 'Xbox Series X',
    price: 50000,
    discountPercent: 5,
    discountPrice: 47500,
    image: 'https://i.gadgets360cdn.com/products/large/xbox-series-x-db-1252x800-1576214218.jpg?downsize=*:180',
    category: 'console',
    rating: 4.2,
    description: 'Enjoy incredible visuals, high-speed performance, and immersive gameplay.',
    trending: false
  },
  {
    _id: "3",
    name: 'Nintendo Switch',
    price: 29999,
    discountPercent:0 ,
    discountPrice: 29000,
    image: 'https://content.hwigroup.net/images/products_1920x1080/381734/nintendo-switch-redblue.jpg',
    category: 'console',
    rating: 2.5,
    description: 'The Nintendo Switch offers versatile and fun gaming experiences.',
    trending: false
  },
  {
    _id: "4",
    name: 'PlayStation 4',
    price: 28000,
    discountPercent: 10,
    discountPrice: 25200,
    image: 'https://ca.easyskinz.com/cdn/shop/collections/download_ae4e1ad6-94c8-40c3-a8b9-1b9a2ec5641c.jpeg?v=1563392053',
    category: 'console',
    rating: 3.8,
    description: 'Experience breathtaking visuals and thrilling gameplay.',
    trending: true
  },
  {
    _id: "5",
    name: 'Xbox One X',
    price: 30000,
    discountPercent: 5,
    discountPrice: 28500,
    image: 'https://pureinfotech.com/wp-content/uploads/2013/05/XboxOne_Consle_Sensr_controllr_780_wide.png',
    category: 'console',
    rating: 3.5,
    description: 'True 4K gaming, enhanced graphics, and immersive sound. With the Xbox One X.',
    trending: false
  },
  {
    _id: "6",
    name: 'Sony DualSense Wireless Controller',
    price: 6000,
    discountPercent: 10,
    discountPrice: 5400,
    image: 'https://images-eu.ssl-images-amazon.com/images/I/51qcJKGmDXL._AC_UL600_SR600,600_.jpg',
    category: 'controller',
    rating: 4.5,
    description: 'Adaptive triggers, haptic feedback, and built-in microphone bring a new level of immersion.',
    trending: true
  },
  {
    _id: "7",
    name: 'Microsoft Xbox Wireless Controller',
    price: 5000,
    discountPercent: 5,
    discountPrice: 4750,
    image: 'https://m.media-amazon.com/images/I/61cIz9OsQOL.jpg',
    category: 'controller',
    rating: 4.3,
    description: 'Sleek design, textured grip, and responsive buttons.',
    trending: false
  },
  {
    _id: "8",
    name: 'Nintendo Switch Pro Controller',
    price: 5500,
    discountPercent: 0,
    discountPrice: 5500,
    image: 'https://m.media-amazon.com/images/I/7166--AaJIL.jpg',
    category: 'controller',
    rating: 2.7,
    description: "Comfortable grip, motion controls, and HD rumble provide an immersive gaming experience.",
    trending: false
  },
  {
    _id: "9",
    name: 'Razer Wolverine Ultimate Controller',
    price: 13000,
    discountPercent: 0,
    discountPrice: 13000,
    image: 'https://m.media-amazon.com/images/I/51gy2QQNy7L._AC_UF1000,1000_QL80_.jpg',
    category: 'controller',
    rating: 3.5,
    description: 'Designed for competitive gamers, this controller features customizable buttons, interchangeable thumbsticks.',
    trending: true
  },
  {
    _id: "10",
    name: 'SteelSeries Stratus Duo Controller',
    price: 7000,
    discountPercent: 10,
    discountPrice: 6300,
    image: 'https://m.media-amazon.com/images/I/51imU4BwUGL._AC_UF1000,1000_QL80_.jpg',
    category: 'controller',
    rating: 3.1,
    description: 'High-performance, lag-free Bluetooth connectivity ensures smooth gameplay.',
    trending: false
  },
  {
    _id: "11",
    name: 'PDP Xbox One Wired Controller',
    price: 3000,
    discountPercent: 0,
    discountPrice: 3000,
    image: 'https://images-cdn.ubuy.co.in/635573b53a6b7011063758f3-pdp-stealth-series-wired-controller-for.jpg',
    category: 'controller',
    rating: 1.5,
    description: 'Comfortable design, textured grip, and precise analog sticks, Detachable 8-foot cable',
    trending: false
  },
  {
    _id: "12",
    name: 'Nacon Revolution Pro Controller',
    price: 7000,
    discountPercent: 20,
    discountPrice: 5600,
    image: 'https://m.media-amazon.com/images/I/61BnB4Mt9hL.jpg',
    category: 'controller',
    rating: 0.5,
    description: 'Advanced customization options, responsive buttons, and ergonomic design.',
    trending: false
  },
  {
    _id: "13",
    name: 'Razer BlackWidow V3 Mechanical Keyboard',
    price: 12500,
    discountPercent: 30,
    discountPrice: 8450,
    image: 'https://m.media-amazon.com/images/I/813VQ1TEBRL._SL1500_.jpg',
    category: 'keyboard',
    rating: 4.1,
    description: 'Mechanical keyboard with Razer Green switches, RGB backlighting with 16.8 million colors, double-shot ABS keycaps, and anti-ghosting',
    trending: true
  },
  {
    _id: "14",
    name: 'HyperX Alloy Elite 2 Mechanical Keyboard',
    price: 14000,
    discountPercent: 30,
    discountPrice: 9800,
    image: 'https://ca.hyperx.com/cdn/shop/products/hyperx_alloy_elite_2_us_2_angled_left_renamed_2.jpg?v=1677079116',
    category: 'keyboard',
    rating: 4.9,
    description: 'Mechanical keyboard with HyperX Red switches, RGB backlighting with 16.8 million colors, dedicated media keys, and anti-ghosting.',
    trending: false
  },
  {
    _id: "15",
    name: 'Cosmic Byte GK-21 Poseidon Mechanical Keyboard',
    price:7500 ,
    discountPercent:15 ,
    discountPrice:6375,
    image: 'https://m.media-amazon.com/images/I/71utzsmU6qL.jpg',
    category: 'keyboard',
    rating: 2.5,
    description: 'Mechanical keyboard with Gateron Brown switches, RGB backlighting with 21 lighting modes, double-shot keycaps, and anti-ghosting.',
    trending: false
  },
  {
    _id: "16",
    name: 'Zebronics Zeb-Max Plus Mechanical Keyboard',
    price: 2000,
    discountPercent: 10,
    discountPrice: 1800,
    image: 'https://zebronics.com/cdn/shop/products/Zeb-Max-V2-pic1.jpg?v=1624529578&width=2048',
    category: 'keyboard',
    rating: 3.6,
    description: 'Mechanical keyboard with Outemu Blue switches, RGB backlighting with 16 lighting modes, double-shot keycaps, and anti-ghosting.',
    trending: false
  },
  {
    _id: "17",
    name: 'Razer DeathAdder Essential Wired Gaming Mouse',
    price: 3000,
    discountPercent: 10,
    discountPrice: 2799,
    image: 'https://i5.walmartimages.com/seo/Razer-DeathAdder-Essential-Wired-Gaming-Mouse-Ergonomic-Mice-with-6400DPI-Optical-Sensor-5-Programmable-Buttons-Black_bef48d85-4fce-46fe-ae2d-c584188ab1b3.9c121a70b12d228d9f8e6a20d203dff3.jpeg?odnHeight=640&odnWidth=640&odnBg=FFFFFF',
    category: 'mouse',
    rating: 4.2,
    description: '6400DPI optical sensor,1000Hz polling rate,Ergonomic design, 10 million clicks, comfortable grip. The anti-slip side skirt effectively increases friction on mouse side.',
    trending: true
  },
  {
    _id: "18",
    name: 'Redgear A-15 Wired',
    price: 2000,
    discountPercent: 25,
    discountPrice: 1500,
    image: 'https://m.media-amazon.com/images/I/61MUoISbzjL._SY355_.jpg',
    category: 'mouse',
    rating: 2.7,
    description: '11 programmable buttons, 16000 DPI optical sensor, RGB backlighting, and ergonomic design.',
    trending: false
  },
  {
    _id: "19",
    name: 'G502 HERO Wired',
    price: 5500,
    discountPercent: 30,
    discountPrice: 3899,
    image: 'https://m.media-amazon.com/images/I/61mpMH5TzkL._SL1500_.jpg',
    category: 'mouse',
    rating: 4.2,
    description: 'High Performance Wired Gaming Mouse, Hero 25K Sensor, 25,600 DPI, RGB, Adjustable Weights, 11 Programmable Buttons, On-Board Memory',
    trending: false
  },
  {
    _id: "20",
    name: 'Razer Viper Ultimate Wireless',
    price: 14999,
    discountPercent: 20,
    discountPrice: 11999,
    image: 'https://m.media-amazon.com/images/I/4178ELACU4L._SL1100_.jpg',
    category: 'mouse',
    rating: 4.8,
    description: 'Wireless Gaming Mouse with Charging,HyperSpeed Lightest Wireless Gaming Mouse with RGB Charging Dock, 8 Programmable Buttons, 20,000 DPI Optical Sensor',
    trending: true
  },
  {
    _id: "21",
    name: 'Logitech G PRO Wireless',
    price: 10500,
    discountPercent: 25,
    discountPrice: 7899,
    image: 'https://m.media-amazon.com/images/I/51ySu55JzAL._SL1500_.jpg',
    category: 'mouse',
    rating: 4.7,
    description: 'Hero 25K Sensor, 25,600 DPI, RGB, Ultra Lightweight, 4-8 Programmable Buttons, Long Battery Life, POWERPLAY-Compatible, Built for Esports,',
    trending: false
  },
  {
    _id: "22",
    name: 'Redgear Cosmo 7.1',
    price: 1500,
    discountPercent: 33,
    discountPrice: 999,
    image: 'https://m.media-amazon.com/images/I/71PhCZEGH7L._SL1500_.jpg',
    category: 'headphone',
    rating: 2.6,
    description: 'Usb Gaming Wired Over Ear Headphones With Mic With Virtual Surround Sound,50Mm Driver, Rgb Leds & Remote Control',
    trending: false
  },
  {
    _id: "23",
    name: 'HyperX Cloud 2',
    price: 11000,
    discountPercent: 30,
    discountPrice: 7699,
    image: 'https://m.media-amazon.com/images/I/71MJ3OaVqBL._SL1500_.jpg',
    category: 'headphone',
    rating: 4.9,
    description: 'Gaming Headset for PC, PS5 / PS4. Includes 7.1 Virtual Surround Sound and USB Audio Control Box',
    trending: true
  },
  {
    _id: "24",
    name: 'Razer BlackShark V2',
    price: 4000,
    discountPercent: 15,
    discountPrice: 3399,
    image: 'https://m.media-amazon.com/images/I/51vUMenoNkL._SL1000_.jpg',
    category: 'headphone',
    rating:3.5,
    description: 'Wired Gaming On Ear Headset - Black, 7.1 Surround Sound-50mm Drivers-Memory Foam Cushion-for PC, PS4, PS5, Switch,Xbox One, Xbox Series X|S, Mobile-3.5mm Audio Jack',
    trending: false
  },
  {
    _id: "25",
    name: 'Logitech G733',
    price:19495 ,
    discountPercent:28,
    discountPrice: 13999,
    image: 'https://m.media-amazon.com/images/I/71RSZdY7pJL._SL1500_.jpg',
    category: 'headphone',
    rating:4.3 ,
    description: 'Lightspeed Bluetooth Wireless On Ear Headphones with Mic Gaming with Suspension Headband, Lightsync RGB, Blue Vo!Ce Mic Technology and Pro-G Audio Drivers',
    trending: false
  },
];
